theme: minima
title: AWS Resume Project
author: Kenneen Cail
description: This is a Resume Im using to test and learn how to use aws cloud services as well as display my talents to perspective partners and employers
